window.OBMSync=function(l){if(window.OBMSyncObject){var a=window.OBMSyncObject;if(l&&"ok"===l.status){if(localStorage["outbrain-msn-uid"]=a.newId,localStorage["outbrain-msn-last-update"]=a.timestamp,l=l.obuid)if(l="https://widgets.outbrain.com/widgetOBUserSync/obUserSync.html#dmpenabled=true&filterDMP=&csenabled=false&d="+l+"&cmpNeeded=false",a=document.getElementById("ob_iframe"),!a){a=document.createElement("iframe");a.setAttribute("id","ob_iframe");var k=a.style;k.display="none";k.width="1px";
k.height="1px";a.src=l||"about:blank";try{document.body.appendChild(a)}catch(p){}}}else localStorage["outbrain-msn-cors-error"]=!0,localStorage["outbrain-msn-last-error"]=a.timestamp}};
(function(){var l=location.protocol+"//sync.outbrain.com/uidmap",a=location.protocol+"//sync.outbrain.com/uidmapjsonp",k=null,p=null,u=null,t=null,x=null,C=null,w=!1,D=!1,E=function(a,b,c){a.open("post",l,!0);a.withCredentials=!0;a.responseType="json";a.onreadystatechange=function(){4===a.readyState&&c(a.response)};a.setRequestHeader("Content-type","application/x-www-form-urlencoded");a.send(b)},G=function(b,c){window.OBMSyncObject={newId:b,timestamp:c};var f="user_id="+b,e=new XMLHttpRequest;!localStorage["outbrain-msn-cors-error"]&&
e&&"withCredentials"in e?E(e,f,window.OBMSync):(localStorage["outbrain-msn-cors-error"]=!0,e=document.createElement("script"),e.src=a+"?"+f,e.async=!0,e.type="text/javascript",(f=document.getElementsByTagName("head")[0])&&f.appendChild(e))},I=function(){window.OB_FIRST_PV="undefined"===typeof window.OB_FIRST_PV?!0:!1;if(window.OB_FIRST_PV&&1===Math.floor(100*Math.random())+1)var a=0,b=setInterval(function(){if(5<=a||w&&F()||v()&&B()){clearInterval(b);var c=v(),e=B(),g=y()?1:0,m=g?F():void 0,l=window.location.href,
k=document.querySelector("meta[property='og:url']");k&&k.getAttribute("content")&&(l=k.getAttribute("content"));var k=localStorage&&!parseInt(localStorage["outbrain-msn-last-error"]||0)&&parseInt(localStorage["outbrain-msn-last-update"]||0)?1:0,n;if(g)a:{try{var p=C;if(p&&window.btoa){var q=p.querySelector(".title"),r=p.querySelector("img"),s=r?window.btoa(encodeURIComponent(r.getAttribute("src")||"")):"";n={title:q?window.btoa(encodeURIComponent(q.textContent||"")):"",imgUrl:s};break a}}catch(u){}n=
{}}else a:{try{q=x;r=null;if(q&&D)p=window.btoa(encodeURIComponent(q.title));else if(q&&window.btoa)var t=q.querySelector("h3"),p=t?window.btoa(encodeURIComponent(t.textContent||"")):"";var z=q.querySelector("img"),r=z?window.btoa(encodeURIComponent(z.getAttribute("src")||"")):"";n={title:p,imgUrl:r};break a}catch(E){}n={}}e="https://log.outbrain.com/loggerServices/pvReport?rate=$RATE&s=$SIDE&f=$FOOTER&h=$ISHOMEPAGE&hp=$HPPROVIDER&sync=$SYNC&extid=$EXTID&url=$URL&tl=$TL&imurl=$IMURL".replace("$RATE",
100).replace("$URL",encodeURIComponent(l)).replace("$SYNC",k).replace("$EXTID",window.OB_extId).replace("$SIDE",c).replace("$FOOTER",e).replace("$ISHOMEPAGE",g).replace("$HPPROVIDER",m).replace("$TL",n.title||"").replace("$IMURL",n.imgUrl||"");c=document.createElement("script");c.setAttribute("src",e);c.setAttribute("charset","UTF-8");c.setAttribute("type","text/javascript");(e=document.getElementsByTagName("head"))&&0<e.length&&e[0].insertBefore(c,e[0].firstChild)}a++},1E3)},y=function(){try{return-1<
document.querySelector("head").getAttribute("data-info").indexOf("PageName:startPage")}catch(a){return!1}},F=function(){if(t)return t;try{var a=n(document.querySelectorAll(".serversidenativead"),[0,1,2]);C=a;var c=a.getAttribute("data-provider");if(c&&c===q("bhgoenva"))var f=a.querySelector(".extnativead")||a.querySelector(".extsource"),c=f&&f.href&&-1<f.href.indexOf("zemanta")?"zemanta":c;return t=c?b(c):void 0}catch(e){}},n=function(a,b){if(!a||!a.length||!b)return null;var c=b[Math.floor(Math.random()*
b.length)];return void 0!==typeof a[c]?a[c]:a[0]},r=function(){if(!0===window.OB_FIRST_PV&&k&&k.cid){var a="https://b1sync.zemanta.com/usersync/msn/?puid="+k.cid,b=document.createElement("img");b.setAttribute("src",a);b.setAttribute("height","1");b.setAttribute("width","1");document.body.appendChild(b)}},q=function(a){return(a+"").replace(/[a-zA-Z]/gi,function(a){return String.fromCharCode(a.charCodeAt(0)+("n">a.toLowerCase()?13:-13))})},v=function(){if(p)return p;try{var a=document.querySelector(".nativeadaside")?
document.querySelector(".nativeadaside").getAttribute("data-provider"):void 0,c=document.querySelector("#aside .trc_rbox_container")?"tf":void 0,f=document.querySelector("#aside .OUTBRAIN")?"of":void 0;return p=b(a)||c||f}catch(e){}},B=function(){if(u)return u;var a=document.querySelector("desktop-feed-views");if(a&&a.shadowRoot)return s();var c;a:{try{var f=n(document.querySelectorAll(".nativeadserversidecontentmodule"),[0,2,4,6]);x=f;var e=f.getAttribute("data-provider");if(e&&e===q("bhgoenva"))var g=
f.querySelector(".extnativead"),e=g&&g.href&&-1<g.href.indexOf("zemanta")?"zemanta":e;c=u=e?b(e):void 0;break a}catch(k){}c=void 0}return c},s=function(){try{var a=document.querySelector("desktop-feed-views");if(a&&a.shadowRoot){var b=a.shadowRoot.querySelectorAll("msft-feed-layout");if(b.length){var c=b[0].shadowRoot.querySelectorAll("msft-article-card"),e=[];Array.prototype.slice.call(c).forEach(function(a){var b;b=a&&a.className?-1===a.className.indexOf("contentCard"):!0;b&&e.push(a)});var g=n(e,
[0,1,2]);if(g)return x=g.querySelector("msft-article"),D=!0,u=encodeURIComponent(z(x.href))}}}catch(k){}},z=function(a){return(a=a.match(/^https?\:\/\/([^\/?#]+)(?:[\/?#]|$)/i))&&a[1]},b=function(a){return a===q("gnobbyn")?"t":a===q("bhgoenva")?"o":a===q("mrznagn")?"z":a},c=function(){if(k){Date.now=Date.now||function(){return+new Date};var a=Date.now(),b=k.cid,c=k.rid;window.OB_extId=c?c:null;I();r();if("undefined"!==typeof Storage&&window.localStorage){var c=localStorage["outbrain-msn-uid"],e=parseInt(localStorage["outbrain-msn-last-update"]||
0),g=parseInt(localStorage["outbrain-msn-last-error"]||0);e+6048E5>a||g+864E5>a||(c&&c!==b&&(localStorage.removeItem("outbrain-msn-uid"),localStorage.removeItem("outbrain-msn-last-update"),localStorage.removeItem("outbrain-msn-last-error")),G(b,a))}}},w=y();window.partnerData?(k=window.partnerData,c()):window.require&&"function"===typeof window.require&&window.require(["nativeadPartnerData"],function(a){k=a?a.getData():null;c()})})();
