(function(){function l(a){a={eventType:"ERROR",configuredProvidersCount:1,configuredReloadCount:1,currentReload:1,description:"MSN script "+a,docId:"2357495582",localTime:(new Date).toString(),orientation:"LANDSCAPE",playerLocation:null,playingType:"UNKNOWN",prebid:!1,provider:"UNKNOWN",providerIndex:1,publisherId:"6478",runningWidgetIdx:0,sourceDocUrl:document.location.href,sourceId:"5419171",sourceWidgetId:"AR_1",subPlatform:"web",timeSinceFirstEvent:null,timeSincePreviousEvent:null,videoClickUrl:null,
videoDuration:0,videoMediaUrl:null,videoProgress:0,videoVastUrl:null,videoViewablePixels:0,viewability:-1,waterfall:null,widgetIdx:0};var d=document.createElement("script");d.setAttribute("src","https://videoevents.outbrain.com/events/recordjp?json="+encodeURIComponent(JSON.stringify(a))+"&callback=OB_VidgetAuditCallback");document.getElementsByTagName("head")[0].appendChild(d)}function a(a){var d="VID_1";try{d="singleCard"===a&&"articlePage"===J?"VID_9":"sliderAlwaysRight"===a?"VID_6":"feedCard"===
a?F():"trackingWidget"===a?"TR_1":"galleryPage"===J?"VID_2":"articlePage"===J?"VID_1":-1<J.toLowerCase().indexOf("startpage")||"ntp"===K?"VID_7":"VID_1"}catch(b){l(b)}return d}function k(){var a=document.getElementsByTagName("head")[0],b=a.getAttribute("data-client-settings")||"",a=a.getAttribute("data-info")||"";J=-1<a.indexOf("PageName:")?a.split("PageName:")[1].split(";")[0]:"";a:{try{JSON.parse(b)}catch(c){a=!1;break a}a=!0}if(b=a?JSON.parse(b):null)b.pagetype&&(K=b.pagetype,d=-1<b.pagetype.indexOf("ntp")),
b.locale&&(a=b.locale.market,b=b.locale.language,m=a&&b?b+"-"+a:"en-us"),M=!!/(mobi|iphone|ipod|symbian|android|windows ce|blackberry|palm|ipad)/i.test(navigator.userAgent);a:{b=document.cookie.length;for(a=0;a<b;){var h=a+10;if("msaOptout="===document.cookie.substring(a,h)){b=h;a=document.cookie.indexOf(";",b);-1===a&&(a=document.cookie.length);e=unescape(document.cookie.substring(b,a));break a}a=document.cookie.indexOf(" ",a)+1;if(0===a)break}e=null}b=(b=document.querySelector("meta[property='og:url']"))&&
b.getAttribute("content")?(b=b.getAttribute("content"))&&/\.msn\./gi.test(b):!1;f=!b;d?L=window.location.protocol+"//www.msn.com/"+m+"/"+K:f&&(L=window.location.origin+window.location.pathname)}function p(){var a=0,d=window.setInterval(function(){var c=w();c&&c.length&&(window.clearInterval(d),u(c));++a===b&&(window.clearInterval(d),c=document.querySelector("body"),u([{type:"trackingWidget",value:c}]))},c)}function u(a){try{for(var b=0;b<a.length;b++){var d=a[b].value,c=y(a[b]),h=q(),f=d.firstChild;
d.insertBefore(h,f);d.insertBefore(c,f)}window.setTimeout(function(){try{if(window.OBR&&window.OBR.extern&&window.OBR.extern.researchWidget)OBR.extern.researchWidget();else{var a=document.createElement("script");a.src="https://widgets.outbrain.com/outbrain.js";var b=document.getElementsByTagName("head")[0];b&&b.appendChild(a)}}catch(d){}},500)}catch(e){l(e)}}function t(a){if(a&&"undefined"!==typeof OB_VIDGET){var b=a.getAttribute("id"),d=a.getAttribute("data-idx");a=a.getAttribute("data-widget-id");
var c=document.getElementById(b+"_"+a+"_playerWrapper");c&&(b=document.querySelectorAll(":not(.OUTBRAIN) video[id]"),Array.prototype.slice.call(b).forEach(function(a){(!(c.getBoundingClientRect().top+c.getBoundingClientRect().height<a.getBoundingClientRect().top||c.getBoundingClientRect().top>a.getBoundingClientRect().top+a.getBoundingClientRect().height||c.getBoundingClientRect().left+c.getBoundingClientRect().width<a.getBoundingClientRect().left||c.getBoundingClientRect().left>a.getBoundingClientRect().left+
a.getBoundingClientRect().width)||0<document.querySelectorAll(".videojs.animate").length)&&OB_VIDGET.pauseResume(d,"pause",!0)}),0===document.querySelectorAll(".videojs.animate").length&&OB_VIDGET.pauseResume(d,"resume",!1))}}function x(a){window.addEventListener("scroll",function(){g&&window.clearTimeout(g);g=window.setTimeout(function(){t(a)},500)})}function C(a){window.addEventListener("onPlay",function(){window.setTimeout(function(){t(a)},500)})}function w(){if(document){var a;if(!(a=I())&&!(a=
D()))a:{a=[];var b=document.querySelector("desktop-feed-views");if(b){var d=b.getAttribute("props-token")||Math.floor(1E3*Math.random()),c=document.querySelectorAll("msft-feed-layout");0===a.length&&(b&&b.shadowRoot)&&(c=b.shadowRoot.querySelectorAll("msft-feed-layout"));if(0===a.length&&0===c.length&&b&&b.shadowRoot)b:{if((c=b.shadowRoot.querySelector("cs-super-container"))&&c.shadowRoot&&(c=c.shadowRoot.querySelector("cs-personalized-feed"))&&c.shadowRoot){A=!0;c=c.shadowRoot.querySelectorAll("cs-feed-layout");
break b}c=[]}M?E(b,c,a,d):G(b,c,a,d);if(0===a.length){a=void 0;break a}}}return a}return null}function D(){var a=[],b=document.querySelectorAll(".contentCard__2x_2y-1");b&&b.length&&Array.prototype.slice.call(b).filter(function(a){try{return a.parentElement.parentElement.className.includes("carousel_tabPanel-1")?!1:!0}catch(b){return!0}}).forEach(function(b){a.push({type:"doubleCard",value:b})});return 0===a.length?void 0:a}function E(a,b,d,c){var h=0;if(b=Array.prototype.slice.call(b)[0]){var f=
b.shadowRoot.querySelectorAll("msft-article-card[size='_1x_2y']");if(f&&(f=Array.prototype.filter.call(f,function(a){return a&&a.className.includes("contentCard")}))&&f.length){var f=f[0],e={width:f.getBoundingClientRect().width,height:f.getBoundingClientRect().height};0<e.width&&0<e.height&&(c="ob-video-"+c+"-"+h++,h=c+"_child",a?(r(b,c,h),r(f,h,null)):r(f,c,null),d.push({type:"feedCard",value:a?a:b,style:e,slotName:c}))}}}function G(a,b,d,c){var h=0,f=0;Array.prototype.slice.call(b).forEach(function(e){h=
b[0].getBoundingClientRect().top;var g=e.shadowRoot.querySelectorAll("msft-article-card[size='_2x_2y']");0===g.length&&A&&(g=e.shadowRoot.querySelectorAll(".card-container[size='_2x_2y']"));Array.prototype.slice.call(g).forEach(function(b){var g=b.getBoundingClientRect().top;if(!(h>=g-50&&h<=g+50)&&(g={width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height},0<g.width&&0<g.height)){var H="ob-video-"+c+"-"+f++,m=H+"_last-child";if(a&&A){var l=H+"_child1",k=H+"_child2",n=H+"_child3";
r(a.shadowRoot.querySelector("cs-super-container"),H,l);r(a.shadowRoot.querySelector("cs-super-container").shadowRoot.querySelector("cs-personalized-feed"),l,k);r(e,k,n);r(b,n,m);r(b.shadowRoot.querySelector(".card-content"),m,null)}else a?(r(e,H,m),r(b,m,null)):r(b,H,null);d.push({type:"feedCard",value:a?a:e,style:g,slotName:H})}})})}function I(){var a=[],b=document.querySelector('[data-section-id="oneriversection"]');b||(b=document.querySelector("#riversection"));if(b){var d=b.querySelectorAll('[data-template-name="RiverCard1uDoubleWide"]');
Array.prototype.slice.call(d).forEach(function(b){a.push({type:"doubleCard",value:b})});var c=b.querySelectorAll(".rc-item-js.rc-item.show[style*='left: 0rem;']");c&&c[1]&&(b=b.querySelectorAll(".rc-item-js.rc-item.show[style*='top: "+c[1].style.top+";']"))&&(2<=b.length&&b[0].querySelector("[data-template-name='RiverCardPhoto']")&&b[1].querySelector("[data-template-name='RiverCardPhoto']")&&b[0].querySelector("[data-template-name='RiverCardPhoto']").offsetHeight===b[1].querySelector("[data-template-name='RiverCardPhoto']").offsetHeight)&&
a.push({type:"singleCard",value:b[0]});(null==e||"0"===e)&&(d&&d[0])&&a.push({type:"sliderAlwaysRight",value:d[0]})}return 0===a.length?void 0:a}function y(b){var d=document.createElement("div");d.setAttribute("class","OUTBRAIN");d.setAttribute("data-widget-id",a(b.type));h&&d.setAttribute("data-external-id",h);d.setAttribute("style","position: absolute;height: 100%;width: 100%;top: 0;");L&&d.setAttribute("data-src",L);if("singleCard"===b.type){var c=d.style,f;f=b.value;var e=document.querySelector('[data-template-name="RiverCard1uDoubleWide"]');
f=e&&0<e.offsetWidth?e.offsetWidth:f.offsetWidth+(f.nextElementSibling.getBoundingClientRect().x-f.getBoundingClientRect().x);c.width=f+"px"}"feedCard"===b.type&&(d.setAttribute("slot",b.slotName),d.style.height=b.style.height+"px",d.style.width=b.style.width+"px",d.style.left="0",d.setAttribute("data-height",b.style.height),d.setAttribute("data-width",b.style.width));"trackingWidget"===b.type&&(d.style.height="1px",d.style.width="1px");return d}function F(){if(A)return"VID_17";switch(K){case "gallery":return n()?
"VID_13":"VID_12";case "article":return M?"VID_16":n()?"VID_11":"VID_10";default:return n()?"VID_15":"VID_14"}}function n(){var a=document.querySelector("msn-verticals-header");return a&&(a=a.shadowRoot.querySelector(".logo"))&&a.title&&"microsoft start"===a.title.toLowerCase()?!0:(a=document.getElementsByTagName("head")[0].getAttribute("data-client-settings")||"")&&a.ocid&&"winp1taskbar"===a.ocid.toLowerCase()?!0:!1}function r(a,b,d){var c=document.createElement("slot");b&&c.setAttribute("name",
b);d&&c.setAttribute("slot",d);a.insertBefore(c,a.firstChild)}function q(){var a=document.createElement("style");a.setAttribute("type","text/css");a.innerHTML=".OUTBRAIN > div:not(#player-place-holder) {z-index: 10 !important;}";a.innerHTML+=".OUTBRAIN[data-widget-id='VID_9'] #close-btn, .OUTBRAIN[data-widget-id='VID_4'] #close-btn {left: auto !important; right: 0 !important; border-width: 0 1px 1px 1px !important;}";return a}function v(){z=!0;window.OB_extId=h?h:window.OB_extId;var a=w();a&&a.length?
u(a):p()}function B(){try{var a=document.getElementsByTagName("head")[0],b=JSON.parse(a.getAttribute("data-client-settings"));b&&b.aid&&(h=b.aid)}catch(d){l(d)}}function s(){if(window.require){var a=window.setTimeout(function(){z||v()},500);window.require(["nativeadPartnerData"],function(b){clearTimeout(a);h=b.getData().rid;z||v()})}else v()}var z=!1,b=4,c=2E3,d=!1,h=null,f=!1,e=null,g=null,m="en-us",K="",J="",L=null,M=!1,A=!1;window.OB_VidgetAuditCallback=function(a){};try{h||B();k();h?v():s();var N=
document.querySelector(".OUTBRAIN[data-widget-id='VID_6']");N&&(x(N),C(N))}catch(O){l(O)}})();
